language: elixir

cache:
  directories:
    - ~/.hex
    - ~/.mix
    - deps

elixir:
  - 1.7
  - 1.8
  - 1.9

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

script:
  - mix test
  - MIX_ENV=test mix dialyzer --halt-exit-status
